---
name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/checkout@v3
      - run: make dep
      - run: make test
      - run: make build
